### ISSUE TITLE
Is duration parameter used?

### ISSUE THREAD

**Issue by qgustavor** [wdavidw/node-csv-generate#3]
I got curious why the generator has a duration parameter. I imagined it was to fix some bug or to prevent infinite memory usage. But seems [it's defined but never used](https://github.com/wdavidw/node-csv-generate/search?utf8=%E2%9C%93&q=duration).

**Comment by wdavidw** [comment]
Not a bug fix. I would have said to generate records for a limited period of time. I think that i planned to implement it but never get that far. I will remove it.
